import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Features from "../components/Features";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landlord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <main>
        <Navbar />
        {/* <nav>
          
          <div class="container">
            <Link href={"/"}>
            </Link>
            <div className="theme">
              <a href="#features">Features</a>
              <a href="">Pricing</a>
              <a href="">FAQ</a>
              <a href="">Connect</a>
            </div>
            <button
              class="theme"
              role="switch"
              aria-label="light/dark mode"
            ></button>
            <audio
              src="audio/light-on.mp3"
              class="theme-audio--light-on"
              data-attribute="adapted from user 160033 file on freesound.org https://freesound.org/people/160033/sounds/366184/ under CC BY-NC 3.0"
            ></audio>
            <audio
              src="audio/light-off.mp3"
              class="theme-audio--light-off"
              data-attribute="adapted from user 160033 file on freesound.org https://freesound.org/people/160033/sounds/366184/ under CC BY-NC 3.0"
            ></audio>
          </div>
        </nav> */}
        <header>
          <div className="meet">
            <h2>
              Enjoy the Security of investing in real estate using Blockchain
              Technology
            </h2>
            <p>
              Whether you are a buyer, seller, or investor in real estate in
              Nigeria, discover the speed, ease and security blockchain
              technology provides you in a thriving digital marketplace.
            </p>
            <a href="#method" className="btn accent1-bg bkg1-link">
              Join Community
            </a>
          </div>
          <div className="meet-img">
            <Image src="/heroimg.png" alt="house" width={800.02} height={664} />
          </div>
        </header>
        <section className="method" id="features">
          <div className="method-header">
            <h3>Your simple roadmap to secure investments</h3>
          </div>
          <div className="cards">
            <Features
              svg={
                <svg
                  width="124"
                  height="197"
                  viewBox="0 0 124 197"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M5.5 135L38.5 100H81.5M5.5 135V143H8.5M5.5 135L46.5 135.5M46.5 143V135.5M46.5 143H8.5M46.5 143L49.7812 140M46.5 135.5L81.5 100M81.5 100L114.5 135.5V143L109 137.667M8.5 143V192M8.5 192L50.5 191.5M8.5 192L2 196H122L116.5 191.88M109 192V137.667M109 192L95 191.88M109 192L114.5 191.88M109 137.667L81.5 111L49.7812 140M49.7812 140L50.5 191.5M50.5 191.5L63.5 191.611M63.5 191.611V169M63.5 191.611L66 191.632M63.5 169V159.5H103L117.5 166V169H116.5M63.5 169H66M66 169V191.632M66 169H84M66 191.632L84 191.786M84 169V191.786M84 169H86.5M84 191.786L86.5 191.808M86.5 169V191.808M86.5 169H114M86.5 191.808L88 191.821M88 191.821V172.5H95V191.88M88 191.821L95 191.88M114 169L114.5 191.88M114 169H116.5M114.5 191.88H116.5M116.5 191.88V169M64 139V144H69V139H64ZM70.5 139V144H75.5V139H70.5ZM64 145.5V150.5H69V145.5H64ZM70.5 145.5V150.5H75.5V145.5H70.5ZM88.5 139V144H93.5V139H88.5ZM95 139V144H100V139H95ZM88.5 145.5V150.5H93.5V145.5H88.5ZM95 145.5V150.5H100V145.5H95ZM22.5 154V159.5H25.5V154H22.5ZM27 154V159.5H29.5V154H27ZM22.5 147.5V153H25.5V147.5H22.5ZM27 147.5V153H29.5V147.5H27ZM30 180.5V186H33V180.5H30ZM34.5 180.5V186H37V180.5H34.5ZM30 174V179.5H33V174H30ZM34.5 174V179.5H37V174H34.5ZM20.5 180.5V186H23.5V180.5H20.5ZM25 180.5V186H27.5V180.5H25ZM20.5 174V179.5H23.5V174H20.5ZM25 174V179.5H27.5V174H25ZM11.5 180.5V186H14.5V180.5H11.5ZM16 180.5V186H18.5V180.5H16ZM11.5 174V179.5H14.5V174H11.5ZM16 174V179.5H18.5V174H16Z"
                    stroke="url(#paint0_linear_626_7535)"
                  />
                  <path
                    d="M26.1016 51.8984L34.2325 43.7675C35.4597 42.5403 37.4688 42.6072 38.6116 43.9133L48.3447 55.0368C49.5035 56.3611 51.548 56.4083 52.7666 55.1389L84.4224 22.1642C85.5698 20.9689 87.4689 20.9302 88.6642 22.0776L96.8025 29.8904C98.0107 31.0503 98.0353 32.9747 96.8571 34.165L52.6412 78.8367C51.4637 80.0264 49.5404 80.0223 48.368 78.8277L26.0819 56.1211C24.9289 54.9465 24.9377 53.0623 26.1016 51.8984Z"
                    stroke="url(#paint1_linear_626_7535)"
                  />
                  <circle
                    cx="62"
                    cy="50"
                    r="49.5"
                    stroke="url(#paint2_linear_626_7535)"
                  />
                  <defs>
                    <linearGradient
                      id="paint0_linear_626_7535"
                      x1="60.5"
                      y1="99"
                      x2="4.89843"
                      y2="299.679"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint1_linear_626_7535"
                      x1="61.2049"
                      y1="18.5064"
                      x2="75.5264"
                      y2="89.0388"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint2_linear_626_7535"
                      x1="61.6065"
                      y1="-2.44846"
                      x2="38.4226"
                      y2="128.112"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                  </defs>
                </svg>
              }
              h4="Verifiable Assets"
              p="Our Blockchain Technology ensure all ownership of listed properties are verifiable and legitimate. "
            />
            <Features
              svg={
                <svg
                  width="156"
                  height="190"
                  viewBox="0 0 156 190"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M44.3728 72.5569H27.4439C25.5629 54.0605 38.7298 17.3651 75.4091 18.0083C118.296 18.7604 128.39 54.6875 128.077 72.5569H111.148C111.148 54.6875 100.99 34.1847 75.4091 34.9371C49.8276 35.6895 44.0593 60.3305 44.3728 72.5569Z"
                    stroke="url(#paint0_linear_626_7521)"
                    strokeWidth="1.88099"
                  />
                  <path
                    d="M27.4439 75.3784H75.4091H128.077C136.353 75.3784 137.795 82.9023 137.482 86.6643V161.904C137.482 169.428 131.212 171.309 128.077 171.309H27.4439C19.1676 171.309 17.7255 165.039 18.0389 161.904V86.6643C18.0389 76.8831 24.3089 75.0649 27.4439 75.3784Z"
                    stroke="url(#paint1_linear_626_7521)"
                    strokeWidth="1.88099"
                  />
                  <g style={{ mixBlendMode: "color-dodge" }}>
                    <path
                      d="M44.3728 72.5569H27.4439C25.5629 54.0605 38.7298 17.3651 75.4091 18.0083C118.296 18.7604 128.39 54.6875 128.077 72.5569H111.148C111.148 54.6875 100.99 34.1847 75.4091 34.9371C49.8276 35.6895 44.0593 60.3305 44.3728 72.5569Z"
                      stroke="url(#paint2_linear_626_7521)"
                      strokeWidth="1.88099"
                    />
                    <path
                      d="M27.4439 75.3784H75.4091H128.077C136.353 75.3784 137.795 82.9023 137.482 86.6643V161.904C137.482 169.428 131.212 171.309 128.077 171.309H27.4439C19.1676 171.309 17.7255 165.039 18.0389 161.904V86.6643C18.0389 76.8831 24.3089 75.0649 27.4439 75.3784Z"
                      stroke="url(#paint3_linear_626_7521)"
                      strokeWidth="1.88099"
                    />
                  </g>
                  <g
                    style={{ mixBlendMode: "color-dodge" }}
                    filter="url(#filter0_f_626_7521)"
                  >
                    <path
                      d="M44.3728 72.5569H27.4439C25.5629 54.0605 38.7298 17.3651 75.4091 18.0083C118.296 18.7604 128.39 54.6875 128.077 72.5569H111.148C111.148 54.6875 100.99 34.1847 75.4091 34.9371C49.8276 35.6895 44.0593 60.3305 44.3728 72.5569Z"
                      stroke="url(#paint4_linear_626_7521)"
                      strokeWidth="1.88099"
                    />
                    <path
                      d="M27.4439 75.3784H75.4091H128.077C136.353 75.3784 137.795 82.9023 137.482 86.6643V161.904C137.482 169.428 131.212 171.309 128.077 171.309H27.4439C19.1676 171.309 17.7255 165.039 18.0389 161.904V86.6643C18.0389 76.8831 24.3089 75.0649 27.4439 75.3784Z"
                      stroke="url(#paint5_linear_626_7521)"
                      strokeWidth="1.88099"
                    />
                  </g>
                  <defs>
                    <filter
                      id="filter0_f_626_7521"
                      x="0.130692"
                      y="0.129715"
                      width="155.259"
                      height="189.049"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity="0" result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation="8.46444"
                        result="effect1_foregroundBlur_626_7521"
                      />
                    </filter>
                    <linearGradient
                      id="paint0_linear_626_7521"
                      x1="77.29"
                      y1="14.2463"
                      x2="130.898"
                      y2="181.654"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint1_linear_626_7521"
                      x1="77.29"
                      y1="14.2463"
                      x2="130.898"
                      y2="181.654"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint2_linear_626_7521"
                      x1="77.29"
                      y1="14.2463"
                      x2="-20.5213"
                      y2="251.251"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint3_linear_626_7521"
                      x1="77.29"
                      y1="14.2463"
                      x2="-20.5213"
                      y2="251.251"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint4_linear_626_7521"
                      x1="81.052"
                      y1="2.96037"
                      x2="26.5034"
                      y2="189.178"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint5_linear_626_7521"
                      x1="81.052"
                      y1="2.96037"
                      x2="26.5034"
                      y2="189.178"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#09FFFF" />
                      <stop offset="1" stopColor="#09FFFF" stopOpacity="0" />
                    </linearGradient>
                  </defs>
                </svg>
              }
              h4="Secure Investments"
              p="Extremely low risk of real estate scam as you carry out Real Estate Investment Trusts (REITs)"
            />
            <Features
              svg={
                <svg
                  width="147"
                  height="147"
                  viewBox="0 0 147 147"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M43 11L73.5 23L104 11L73.5 0L43 11Z"
                    fill="#09FFFF"
                  />
                  <path
                    d="M104 11L73.5 23V61L104 49V11Z"
                    fill="url(#paint0_linear_626_7528)"
                  />
                  <path
                    d="M73.5 23L43 11V49L73.5 61V23Z"
                    fill="url(#paint1_linear_626_7528)"
                  />
                  <path
                    d="M85.5 96L116 108L146.5 96L116 85L85.5 96Z"
                    fill="#09FFFF"
                  />
                  <path
                    d="M146.5 96L116 108V146L146.5 134V96Z"
                    fill="url(#paint2_linear_626_7528)"
                  />
                  <path
                    d="M116 108L85.5 96V134L116 146V108Z"
                    fill="url(#paint3_linear_626_7528)"
                  />
                  <path
                    d="M0 96.5L30.5 108.5L61 96.5L30.5 85.5L0 96.5Z"
                    fill="#09FFFF"
                  />
                  <path
                    d="M61 96.5L30.5 108.5V146.5L61 134.5V96.5Z"
                    fill="url(#paint4_linear_626_7528)"
                  />
                  <path
                    d="M30.5 108.5L0 96.5V134.5L30.5 146.5V108.5Z"
                    fill="url(#paint5_linear_626_7528)"
                  />
                  <path
                    d="M56.5 37C57.7 34.6 55.6667 33.6667 54.5 33.5L28.5 43.5V95.5C30.5 96.7 32.3333 96 33 95.5V46.5L56.5 37Z"
                    fill="#68607C"
                  />
                  <path
                    d="M90.5 37C89.3 34.6 91.3333 33.6667 92.5 33.5L118.5 43.5V95.5C116.5 96.7 114.667 96 114 95.5V46.5L90.5 37Z"
                    fill="#68607C"
                  />
                  <path
                    d="M42 123C40.4 119.4 42.6667 118.167 44 118L73 129.5L102 118.5C104.8 118.1 105.167 121 105 122.5L73 135L42 123Z"
                    fill="#68607C"
                  />
                  <defs>
                    <linearGradient
                      id="paint0_linear_626_7528"
                      x1="73.5"
                      y1="-1.07843e-06"
                      x2="88.5"
                      y2="72.5"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#087780" />
                      <stop offset="0.62917" stopColor="#086B7A" />
                      <stop offset="1" stopColor="#087780" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint1_linear_626_7528"
                      x1="73.25"
                      y1="-3.57872e-08"
                      x2="74.4508"
                      y2="170.516"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#0B1E61" />
                      <stop
                        offset="0.697037"
                        stopColor="#0E2163"
                        stopOpacity="0.65"
                      />
                      <stop offset="1" stopColor="#0E2163" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint2_linear_626_7528"
                      x1="73.5"
                      y1="2.22885e-06"
                      x2="88"
                      y2="133"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#087780" />
                      <stop offset="0.62917" stopColor="#086B7A" />
                      <stop offset="1" stopColor="#087780" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint3_linear_626_7528"
                      x1="73.25"
                      y1="-3.57872e-08"
                      x2="74.4508"
                      y2="170.516"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#0B1E61" />
                      <stop
                        offset="0.697037"
                        stopColor="#0E2163"
                        stopOpacity="0.65"
                      />
                      <stop offset="1" stopColor="#0E2163" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint4_linear_626_7528"
                      x1="73.5"
                      y1="2.22885e-06"
                      x2="88"
                      y2="133"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#087780" />
                      <stop offset="0.62917" stopColor="#086B7A" />
                      <stop offset="1" stopColor="#087780" stopOpacity="0" />
                    </linearGradient>
                    <linearGradient
                      id="paint5_linear_626_7528"
                      x1="73.25"
                      y1="-3.57872e-08"
                      x2="74.4508"
                      y2="170.516"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#0B1E61" />
                      <stop
                        offset="0.697037"
                        stopColor="#0E2163"
                        stopOpacity="0.65"
                      />
                      <stop offset="1" stopColor="#0E2163" stopOpacity="0" />
                    </linearGradient>
                  </defs>
                </svg>
              }
              h4="Complete Transparency"
              p="Our Technology ensures that all transactions carried out is built on a distributed ledger system to avoid tampering."
            />
          </div>
        </section>
        <section id="info" className="info">
          <div className="info-container">
            <div className="img">
              <Image
                src="/coin.png"
                alt="house"
                width={830.14}
                height={661.61}
              />
            </div>
            <div className="info-text">
              <h3>Who are We?</h3>
              <p>
                Landlords is a platform that understands the hassle involved in
                trying to buy or sell a property especially due to the risk of
                scammers, or illegal transactions associated to traditional real
                estate acquisition and investing.<br></br>
                <br></br> Our platform built with blockchain technologyprovides
                real estate agencies, property owners, investors, and
                individuals looking to buy, sell, or invest with security, speed
                and convinence within a thriving digital ecosystem.
              </p>
            </div>
          </div>
        </section>
        <section id="meet-team">
          <h3>Meet The Team</h3>
          <div className="team">
            <div className="item">
              <Image
                src="/Paul.jpg"
                width={344.16}
                height={430.41}
                alt="image of product/visual designer"
              />
              <h4>Paul C. Esike Jr</h4>
              <p>Product/ Visual Designer</p>
            </div>
            <div className="item">
              <Image
                src="/Ibrahim.jpg"
                width={344.16}
                height={430.41}
                alt="image of software developer"
              />
              <h4>Ibrahim Yakubu</h4>
              <p>Software Engineer</p>
            </div>
            <div className="item">
              <Image
                src="/Olatunde.jpg"
                width={344.16}
                height={430.41}
                alt="image of product designer"
              />
              <h4>Olatunde Aina</h4>
              <p>Lead Product Designer</p>
            </div>
          </div>
        </section>
        <section id="possibilities">
          <div className="possibilities">
            <h3>Are You Ready To Explore The Endless Possibilities?</h3>
            <p>
              Our Secure Network and fast growing marketplace combined with your
              personal needs, allows us create an investment plan specifically
              tailored to your needs
            </p>
            <a href="#method" className="btn accent1-bg bkg1-link">
              Join Community
            </a>
          </div>
        </section>
        <section id="cta">
          <Image
            src="/buttom.png"
            alt="digital bank"
            width={830.14}
            height={661.61}
          />
        </section>
      </main>

      <footer id="footer">
        <div className="footer">
          <div className="subscribe">
            <h4>Subscribe to our quarterly Newsletter</h4>
            <input
              className="input"
              type={"text"}
              placeholder="enter your email"
            />
            <a className="btn accent1-bg bkg1-link" type="button">
              Submit
            </a>
          </div>
          <div className="wrapper">
            <Image
              src="/landlord logo 3.svg"
              alt="logo"
              width={334.26}
              height={334.26}
            />
            <div className="footer-link">
              <h4>Landlord</h4>
              <a>Home</a>
              <a>About</a>
              <a>Blog</a>
              <a>Contact</a>
            </div>
            <div className="footer-link">
              <h4>Resources</h4>
              <a>Contact</a>
              <a>Partners</a>
              <a>Help desk</a>
              <a>newsletter</a>
            </div>
            <div className="footer-link">
              <h4>Events</h4>
            </div>
            <div className="footer-link">
              <h4>Follow</h4>
            </div>
          </div>
          <div>
            <a>Terms & Conditions</a>
            <a>Privacy Policy</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
